# This workflow will install the node_modules, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/bootstrap
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run linter, concat, minifier and tests
      run: yarn dist
